### ISSUE TITLE
Having problems with trader mood

### ISSUE THREAD

**Issue by crisian123** [Lu-Yi-Hsun/iqoptionapi#141]
Hello! First, thank for your effort :D
I am trying to write this example. 

import time
import logging
import scipy.io
import numpy as np
from iqoptionapi.stable_api import IQ_Option

I_want_money=IQ_Option("my email","my pasword")
goal="EURUSD-OTC"
A1 = I_want_money.get_traders_mood(goal)

but I recieve this error 

Traceback (most recent call last):

  File "<ipython-input-4-e02ecf98feba>", line 1, in <module>
    I_want_money.get_traders_mood(goal)

  File "C:\ProgramData\Anaconda3\lib\site-packages\iqoptionapi\stable_api.py", line 589, in get_traders_mood
    return self.api.traders_mood[OP_code.ACTIVES[ACTIVES]]

KeyError: 76

and I don't know why. :(
I am using spyder. and Until now I could to get candles normally. And now I am traing to see the mood. but I can't

**Comment by JafferWilson** [comment]
When did you tried this example? Is this example tried when the OTC was working and rest of the Currencies were off? What is the version of API you are using? Please specify your condition in which you get this error.

**Comment by crisian123** [comment]
I tryied this today (when the OTC option was available), and also tryied with another for example AUDUSD-OTC. but the same error. And I installed the api 3 days ago. 
I am not an experto on python. but if I remember well a keyError is when the program can not to find that name on list. 
self.api.traders_mood[OP_code.ACTIVES[ACTIVES]] -----> list
KeyError: 76 -------> AUDUSD-OTC not found on list. 
mean the list is empty indeed..... (?)

**Comment by Lu-Yi-Hsun** [comment]
https://github.com/Lu-Yi-Hsun/iqoptionapi#get-mood
 ```python
from iqoptionapi.stable_api import IQ_Option
I_want_money=IQ_Option("email","password")
goal="EURUSD"
I_want_money.start_mood_stream(goal)
print(I_want_money.get_traders_mood(goal))
I_want_money.stop_mood_stream(goal)
```
please add start_mood_stream

**Comment by crisian123** [comment]
Oh I see. I forgot to start the mood stream. thank you for the help :) Now works very well.

**Comment by rrfaria** [comment]
could have an option to each type.
for instance I use forex then it could be better to me analyse
