### ISSUE TITLE
FREE API NOT RUN

### ISSUE THREAD

**Issue by danielpetrato** [Lu-Yi-Hsun/iqoptionapi#202]
A free version has been blocked and is not available to run.

Traceback (most recent call last):
  File "BOB.py", line 2, in <module>
    from iqoptionapi.stable_api import IQ_Option
  File "C:\Users\danie\Desktop\BOB_CONNECTOR\iqoptionapi-master\iqoptionapi\stable_api.py", line 2, in <module>
    from iqoptionapi.api import IQOptionAPI
  File "C:\Users\danie\Desktop\BOB_CONNECTOR\iqoptionapi-master\iqoptionapi\api.py", line 7, in <module>
    import requests
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\__init__.py", line 112, in <module>
    from . import utils
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\compat.py", line 59, in <module>
    from http import cookiejar as cookielib
  File "C:\Users\danie\AppData\Local\Programs\Python\Python36-32\lib\http\cookiejar.py", line 31, in <module>
    import copy
  File "C:\Users\danie\Desktop\BOB_CONNECTOR\iqoptionapi-master\copy.py", line 2, in <module>
    from iqoptionapi.stable_api import IQ_Option
ImportError: cannot import name 'IQ_Option'

**Comment by provezano** [comment]
It's working here...
Unsubstantiated statement.

**Comment by vish4mi** [comment]
I tried even...Don't work. Not even compiling.
