### ISSUE TITLE
buy or sell not work , 'IQ_Option' object has no attribute 'api'

### ISSUE THREAD

**Issue by Aleandro21** [Lu-Yi-Hsun/iqoptionapi#219]
Why don't work ?

python test.py
get candles
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    print(I_want_money.get_candles(goal,60,111,time.time()))
  File "/usr/local/lib/python3.5/dist-packages/iqoptionapi/stable_api.py", line 451, in get_candles
    self.api.candles.candles_data = None
AttributeError: 'IQ_Option' object has no attribute 'api'

**Comment by RobbOliver** [comment]
I_want_money = IQ_Option("email", "password")
check, reason = I_want_money.connect()

You need add .connect()

**Comment by bissamrck** [comment]
hwo can'i add .connect() ???

**Comment by TheHolsback** [comment]
Where is the code?

**Comment by bissamrck** [comment]
I_want_money = IQ_Option('email','password')
check = I_want_money.connect()
if check:
    print("####connect successfully####")
else:
    print("####connect failed####")

goal=input("enter Asset :")
print("balance : ", I_want_money .get_balances())
check = I_want_money.connect()
   line 90, in connect
    self.api.set_session(headers=self.SESSION_HEADER, cookies=self.SESSION_COOKIE)
AttributeError: 'IQOptionAPI' object has no attribute 'set_session'

**Comment by duber23-20** [comment]
velas = API.get_candles(par, int(timeframe) * 60, 20, time.time())
  File "C:\Python37\lib\site-packages\iqoptionapi-6.8.9.1-py3.7.egg\iqoptionapi\stable_api.py", line 454, in get_candles
    self.api.candles.candles_data = None
AttributeError: 'IQ_Option' object has no attribute 'api'

**Comment by rochapedro07** [comment]
check, id = API.buy_digital_sport_v2(ativo,valor,direcao,exp)

AttributeError: 'IQ_Option' object has no attribute 'buy_digital_sport_v2'


nao consigo resolver esse problema

**Comment by cesano-cmd** [comment]
spot,    non sport
