### ISSUE TITLE
I have this problem

### ISSUE THREAD

**Issue by techdavi** [Lu-Yi-Hsun/iqoptionapi#339]
ERROR:root:buy_digital_spot active error
Traceback (most recent call last):
  File "C:\Users\davij\OneDrive\Área de Trabalho\OPÇÕES\run.py", line 110, in <module>
    bot.polling()
  File "C:\Users\davij\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 946, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\davij\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 1021, in __threaded_polling
    raise e
  File "C:\Users\davij\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 977, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\davij\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 154, in raise_exceptions
    raise self.exception_info
  File "C:\Users\davij\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 98, in run
    task(*args, **kwargs)
  File "C:\Users\davij\OneDrive\Área de Trabalho\OPÇÕES\run.py", line 88, in operar_lista
    status, id = API.buy_digital_spot(str(sinal[2]), int(sinal[3]), str(sinal[4]), int(sinal[5]))
TypeError: cannot unpack non-iterable int object

**Comment by TheHolsback** [comment]
post the code to us know what happenig :)

**Comment by techdavi** [comment]
problem solved
